on: push

name: Docker build and push

permissions:
  contents: write
  packages: write
  security-events: write
  actions: read

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to GHCR
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        load: ${{ github.ref != 'refs/heads/main' }}
        context: .
        file: ./docker/Dockerfile
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ github.sha }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
        push: ${{ github.ref == 'refs/heads/main' }}
    - name: Tag v1
      run: git tag --force v1 && git push --tags --force
